# Generated by Django 3.2.2 on 2021-05-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roaryapp', '0002_alter_roar_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roar',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
